"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Brand } from "@/components/brand";
import { PageTitle, ProfileView } from "@/components/student-pages";
import styles from "./mentor-pages.module.css";

const lessons = ["Front End with React : Basics", "Node.js for backend", "Basics Of JavaScript", "UI Design Systems"];

export function MentorMarketingPage(){ return <main className={styles.marketing}><section className={styles.hero}><header><Brand/><nav><a href="#categories">Category</a><a href="#about">About Us</a><a href="#business">Upskillink Business</a></nav><Link href="/login">Sign Up　→</Link></header><span>WELCOME TO UPSKILLINK</span><h1>Meet the Professional<br/>Mentor</h1><div className={styles.quote}><b>“</b><p>Now you can teach anywhere, anytime, and build an independent career.</p><strong>10K+<small>Mentors</small></strong></div><Image src="/assets/app/mentor-marketing-hero.png" alt="Professional mentor" width={500} height={560} priority/><div className={styles.rating}>★★★★★<p>“Personalized tutoring on this platform transformed my teaching experience.”</p></div><div className={styles.heroActions}><Link href="/onboarding/mentor">Request Demo　↗</Link><Link href="/onboarding/mentor">I’m Mentor</Link></div></section><section className={styles.mentorAbout} id="about"><span>WHY UPSKILLINK</span><h2>Turn your experience into impact</h2><div><article><b>01</b><h3>Accept a lesson</h3><p>Choose requests that match your skills and schedule.</p></article><article><b>02</b><h3>Connect with learners</h3><p>Conduct practical, personalized live sessions.</p></article><article><b>03</b><h3>Earn rewards</h3><p>Grow your reputation and professional network.</p></article></div></section><section className={styles.mentorCta}><h2>Start mentoring on your terms.</h2><Link href="/onboarding/mentor">Become a mentor　→</Link></section></main>; }

export function MentorHomePage(){ return <AppShell active="/mentor/home" mentor><main className={styles.main}><section className={styles.pro}><div><h1>Become a Pro Member</h1><p>Unlimited access to 2000+ mentors, courses, community and daily free lessons.</p><Link href="/subscription">Register Now　↗</Link></div><Image src="/assets/onboarding/waiting.png" alt="" width={250} height={180}/></section><section className={styles.homeGrid}><article className={styles.panel}><h2>Lesson Requests</h2>{lessons.concat(lessons.slice(0,2)).map((name,i)=><Link href="/mentor/bookings" key={`${name}${i}`}><span>◉</span><b>{name}<small>{["08:00 - 10:00","12:00 - 14:00","18:00 - 19:00"][i%3]}</small></b><strong>₹ {i%2?"75":"300"}</strong></Link>)}</article><aside className={styles.panel}><h2>Schedule</h2><p>Mon　Tue　Wed　<b>Thu</b>　Fri</p><article><b>Basics Of JavaScript</b><small>March 24 at 4:00 PM</small><Link href="/meeting">View</Link></article><article><b>Backend With Django</b><small>March 25 at 4:00 PM</small></article></aside></section><section className={styles.panel}><h2>Top Mentors</h2><div className={styles.people}>{[1,2,3,4].map(i=><span key={i}><Image src={`/assets/app/mentor-${i}.png`} alt="" width={55} height={55}/><b>Kristin Watson<small>Top Tutor</small></b></span>)}</div></section></main></AppShell>; }

export function MentorBookingsPage(){ const [bid,setBid]=useState(false); return <AppShell active="/mentor/bookings" mentor><main className={styles.main}><PageTitle>Accept Lesson</PageTitle><section className={styles.booking}><article className={styles.panel}><h2>Node.js For Backend</h2><p>▣ 9 April 2020　 ◷ 12.00 - 14.00</p><div><h3>Description</h3><p>I want to learn the fundamentals of JavaScript for web development. I’m interested in variables, data types, control structures, functions and loops.</p></div><div><h3>Tags</h3><p>{["JS","Coding","Loops","Programming","Variables","Functions","Basics","Interactive","DataTypes","Web"].map(x=><b key={x}>{x}</b>)}</p></div><h2>Resources</h2><label className={styles.upload}>⇧<input type="file"/>Click to upload or drag and drop<br/>SVG, PNG, JPG or GIF</label></article><aside className={styles.panel}><h2>Bill</h2><p>Live Lesson <b>₹300</b></p><p>Platform Fees <b>-₹20</b></p><hr/><strong>Total　₹400</strong><textarea placeholder="Feedback"/><div><button onClick={()=>setBid(true)}>Counter Bid</button><Link href="/meeting">Accept</Link></div></aside></section>{bid&&<div className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="bid-title"><form onSubmit={e=>{e.preventDefault();setBid(false)}}><h2 id="bid-title">Make a counter offer</h2><label>New Bid<input type="number" defaultValue="400" min="1"/></label><label>Feedback<textarea defaultValue="The topic requires additional time and preparation."/></label><button>Offer</button><button type="button" onClick={()=>setBid(false)}>Cancel</button></form></div>}</main></AppShell>; }

export function MentorLessonsPage(){ return <AppShell active="/mentor/lessons" mentor><main className={styles.main}><PageTitle>Lessons</PageTitle><nav className={styles.lessonTabs}><b>Upcoming</b><span>Completed</span><span>Drafts</span></nav><section className={styles.lessonList}>{lessons.map((name,i)=><article className={styles.panel} key={name}><Image src={`/assets/app/course-${["design","css","data","design"][i]}.png`} alt="" width={220} height={160}/><div><small>{i<2?"UPCOMING":"COMPLETED"}</small><h2>{name}</h2><p>12 Lessons　 ◷ 1h 14m</p><p>Student: Bhubnesh Maharana</p></div><Link href={i<2?"/meeting":"/mentor/bookings"}>{i<2?"Start class":"View details"}</Link></article>)}</section></main></AppShell>; }

export function MentorProfilePage(){ return <ProfileView mentorApp/>; }

export function MentorDashboardPage(){ const leaders=["Charlie Rawal","Ariana Agarwal","Bhubnesh Maharana","Kiran"]; return <AppShell active="/mentor/dashboard" mentor><main className={styles.main}><PageTitle>Dashboard</PageTitle><section className={styles.summary}><div>₹10,000<small>Total Earning</small></div><div>240 hrs<small>Total Teaching</small></div><div>12<small>Total lessons</small></div></section><section className={styles.dashboard}><article className={styles.panel}><h2>Hours Sent</h2><div className={styles.bars}>{[65,40,72,50,25,76,70].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div><p>Jan　 Feb　 Mar　 Apr　 May　 Jun　 Jul</p></article><aside className={styles.panel}><h2>Available Credit</h2><strong>₹2,350</strong><p>Your current balance</p><Link href="/payment">Add Credits　↗</Link></aside><article className={styles.panel}><h2>Leader Board</h2>{leaders.map((x,i)=><p className={styles.leader} key={x}><b>{i+1}</b>{x}<strong>{13-i}.450</strong></p>)}</article><aside className={styles.panel}><h2>Credit score</h2><strong className={styles.score}>821</strong><p>Your Reputation Points</p></aside></section></main></AppShell>; }
