export type Skill = { id: string; slug: string; name: string };
export type MentorProfile = {
  profile_id: string;
  headline: string | null;
  bio: string | null;
  hourly_rate_minor: number;
  currency: string;
  languages: string[];
  professions: string[];
  companies: string[];
  approval_status: string;
  rejection_reason: string | null;
};
export type Profile = {
  id: string;
  role: "student" | "mentor";
  onboarding_status: string;
  first_name: string;
  last_name: string;
  username: string | null;
  phone: string | null;
  location: string | null;
  avatar_path: string | null;
  bio: string | null;
  skills: Skill[];
  mentor: MentorProfile | null;
};
export type Mentor = {
  id: string;
  first_name: string;
  last_name: string;
  username: string | null;
  avatar_path: string | null;
  headline: string | null;
  bio: string | null;
  hourly_rate_minor: number;
  currency: string;
  languages: string[];
  professions: string[];
  companies: string[];
  average_rating: number;
  review_count: number;
};
export type LessonRequest = {
  id: string;
  student_id: string;
  preferred_mentor_id: string | null;
  title: string;
  description: string;
  requested_start: string;
  requested_end: string;
  proposed_amount_minor: number;
  currency: string;
  status: string;
};
export type Offer = { id: string; request_id: string; mentor_id: string; amount_minor: number; currency: string; note: string | null; status: string; created_at: string };
export type Booking = { id: string; student_id: string; mentor_id: string; starts_at: string; ends_at: string; amount_minor: number; currency: string; status: string };
export type Review = { id: string; booking_id: string; student_id: string; mentor_id: string; rating: number; comment: string | null; created_at: string };
export type Plan = { id: string; slug: string; name: string; price_minor: number; currency: string; billing_interval: string; features: string[] };
